### ISSUE TITLE
3.0.0-alpha.10 - SnackbarContent - Property 'ref' does not exist on type 'IntrinsicAttributes & SnackbarContentProps'

### ISSUE THREAD

**Issue by talatkuyuk** [iamhosseindhv/notistack#521]
With 3.0.0-alpha.07, the below implementation was fine, has no error;

But,

After upgrading 3.0.0-alpha.07 to 3.0.0-alpha.10, I've started to receive the error below in the Custom snackbar component

`
Type '{ children: Element; className?: string | undefined; style: CSSProperties; variant: "default" | "error" | "success" | "warning" | "info" | "apiresponse" | "validationerror"; action?: SnackbarAction; ref: ForwardedRef<...>; role: "alert"; }' is not assignable to type 'IntrinsicAttributes & SnackbarContentProps'.
`

`
Property 'ref' does not exist on type 'IntrinsicAttributes & SnackbarContentProps'.
`

```ts
const SnackbarApiResponse = forwardRef<HTMLDivElement, CustomSnackbarProps>(
  function SnackbarApiResponseInner(props, ref) {
    const {
      id,
      message,
      autoHideDuration,
      anchorOrigin,
      hideIconVariant,
      iconVariant,
      persist,
      header, // custom prop
      status, // custom prop
      ...other
    } = props;

    const svgPath = `/${status}.svg`;

    return (
      <SnackbarContent ref={ref} role="alert" {...other}>   // <--------------- here, I receive the error
        <Container status={status}>
          <Wrapper>
            <Image style={{ marginInlineEnd: "0.5rem" }} src={svgPath} width={24} height={24} alt={status} />
            <MainContent>
              <MainFirstLine>{header}</MainFirstLine>
              <MainSecondLine>{message}</MainSecondLine>
            </MainContent>
            <Action snackbarId={id} status={status} />
          </Wrapper>
        </Container>
      </SnackbarContent>
    );
  }
);
```

I suppose it is related with the type `SnackbarContentProps` in the `index.d.ts` file:

```ts
export type SnackbarContentProps = React.HTMLAttributes<HTMLDivElement>;

// could be like below, seems the ref error is gone
export type SnackbarContentProps = React.HTMLAttributes<HTMLDivElement> & React.RefAttributes<HTMLDivElement>;
```

## Your Environment
react18, typescript 4.8.4, notistack 3.0.0-alpha.10

**Comment by talatkuyuk** [comment]
With the version 3.0.0-alpha.11, the error is gone, thanks.

**Comment by iamhosseindhv** [comment]
@talatkuyuk Thanks for reporting the bug. It should be fixed in the latest `alpha` version (`v3.0.0-alpha.11`)
